// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plzmnpbzqbmdbbxdpgwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsem1ucGJ6cWJtZGJieGRwZ3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTA0NjIsImV4cCI6MjA2ODU4NjQ2Mn0._UeV30YVj68ivtbQubAhU3fZVf9MgzfRZvSh31btZcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});